### ISSUE TITLE
Feature request, logging

### ISSUE THREAD

**Issue by aWitch-Doctor** [Erigitic/TotalEconomy#169]
Can you add the ability to log all transactions?

Nothing fancy, just a text file that's put on the server that records the server time, what plugin caused the transfer, what player lost money, that players old and new balance, what player gained money, that players old and new balance, and the amount of the transfer. It will need to show if the money comes or goes to the server as well. I don't think it's possible but if you could also make it show what command was ran to cause the money transfer that would be amazing. 

Since you added sql support you could use that instead of a file, maybe make it in game commands (command ideas below), go hog wild on it if you want but all i need is a simple log file.

If the log file is easy to do then I would like to get that quickly and then if you feel generous work on sql support and commands later? I'm having a lot of issues with other plugins not moving money correctly and that is expected since they are mostly beta but when i try to fix the problems for the players it takes sooo long since I can't really find any info on it.

/te history [name/amount/plugin] [number of past transactions] - shows the past X number of transactions involving that name/amount/plugin, number of transactions can be optional. If it's not specified by the command then it defaults to config setting.

**Comment by MarkL4YG** [comment]
I sounds interesting. I think I may create something like that and publish a dev version for you just as an aid. @Erigitic can decide whether or not this kind of a debugging tool should be staticly implemented, however I would think that transaction histories can be a good thing to have for bigger servers who may have virtual accounts for companies or even banks.

**Comment by MarkL4YG** [comment]
@aWitch-Doctor I've quickly assembled a plugin that can write some of the TransactionEvents information to the console or to a file. The output looks like this:
```
## BEGIN TRANSACTION ##
  Type: deposit
  Account: f51311ea-5401-3129-9c49-1c45d0b70a40/mark332
  Amount: 108.00 $
  Amount-After: 108.00
  Result: SUCCESS
  Class: com.erigitic.config.TEEconomyTransactionEvent
  Named causes:
    TotalEconomy: org.spongepowered.mod.plugin.SpongeModPluginContainer
  Contexts:
## END TRANSACTION ##
```
I've uploaded the plugin AND a sources jar (if you would like to look at the source first) to Google-Drive for you: https://drive.google.com/drive/folders/0B-XTkzS0225PTnBBc2FJYVhZUTQ?usp=sharing
Just in case this may help you debugging your problem.
